#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run the build
npm run build

# Check for unstaged changes after build
if [ -n "$(git status --porcelain)" ]; then
  echo "Staging changes after the build process."
  git add .
fi